apiVersion: v1
kind: Service
metadata:
  name: pizza-app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.pizza_app.container.port }}
      targetPort: {{ .Values.services.pizza_app.container.port }}
  selector:
    app: pizza-app
